name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */24 * * *"  # runs every 24 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: krishna18developer
          svg_out_path: output/github-contribution-grid-snake.svg
          snake_color: 'blue'
          
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Generate Snake Animation'
          add: 'output'
