name: Generate Snake Animation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: krishna18developer
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          add: dist/github-contribution-grid-snake.svg
          message: "Update GitHub contribution snake"
          push: true
